version: '3.8'

services:
  db:
    container_name: postgresql_db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pg@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=postgres
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - db
